server:
  port: 7777
spring: 
  application:
    name: spring-cloud-quartz-center
  quartz:
      #相关属性配置
    properties: 
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/quartz?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: lihuiquan1992
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: 
  - classpath:mapping/*.xml
  type-aliases-package: com.lhq.cloud.quartz.entity