spring:
  zipkin:
    locator:
      discovery:
        enabled: true
    base-url:  http://localhost:7001/
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: spring-cloud-zuul-center
server:
  port: 80
zuul:
  routes:
    provider:                                               # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /provider/**                                    # 想要映射到的路径
      service-id: spring-cloud-service-provider           # Eureka中的serviceId
    consumer:                                               # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /consumer/**                                    # 想要映射到的路径
      service-id: spring-cloud-fegin-consumer           # Eureka中的serviceId
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    metadata-map:
      zone: zone1
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    region: changsha
    availability-zones:
      changsha: zone1,zone2
    serviceUrl:
      zone1: http://localhost:9001/eureka/,http://localhost:9002/eureka/
      zone2: http://localhost:9003/eureka/