dkd:
  security:
    browser:
      loginType: JSON
      signInPage: /login.html
security:
  user:
    password: 123456
server:
  context-path: /server
  port: 9001
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8mb4
    username: root
  session:
    store-type: none