spring:
  application:
    name: spring-cloud-zuul-gateway
server:
  port: 80
eureka:
  instance:
  client:
    serviceUrl:
      defaultZone:  http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9003/eureka/
zuul:
  routes:
    user:                                               # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /test/**                                    # 想要映射到的路径
      service-id: spring-cloud-service-provider           # Eureka中的serviceId