spring:
  cloud:
    stream:
      binders:
        test:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: 192.168.175.41:5672,192.168.175.42:5672,192.168.175.43:5672
                username: admin
                password: admin
                virtual-host: /unicode-paya
      bindings:
        testInPut:
          destination: testRabbit
          content-type: application/json
          default-binder: test
server:
  port: 8080