server:
  port: 9000
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      label: master
      server: 
        git: 
          uri: https://github.com/SusizeChina/spring-cloud-config
          search-paths: /{application}
          username: 
          password: 
eureka: 
  instance: 
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    metadata-map: 
      zone: zone1
  client: 
    register-with-eureka: true
    fetch-registry: true
    prefer-same-zone-eureka: true
    region: changsha
    availability-zones:
      changsha: zone1,zone2
    serviceUrl: 
      zone1: http://localhost:9001/eureka/,http://localhost:9002/eureka/
      zone2: http://localhost:9003/eureka/